# --------------------------------------------------------------------------
# HD44780 library for PIC microcontrollers
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pic-toolchain
# 
# --------------------------------------------------------------------------

PROJECT=hd44780_lcd
EXTRA_C=lcd_lib.c
EXTRA_ASM=lcd_delay.asm
MODEL=12f675
ARCH=pic14
SDCC_ARGS=-DLCD_PRINT_X
include rules.inc

# --------------------------------------------------------------------------
